public class sum {
    public void add(){
        integer a=40;
        integer b=40;
        integer z;
        z=a+b;
        system.debug('addition='+z);
        
    }
    public void sub(){
        integer a=40;
        integer b=40;
        integer z;
        z=a-b;
        system.debug('subtraction='+z);
    }
    public void mul(){
        integer a=40;
        integer b=40;
        integer z;
        z=a*b;
        system.debug('multiplication='+z);
    }
    public void div(){
        integer a=40;
        integer b=40;
        integer z;
        z=a/b;
        system.debug('division='+z);
    }

}