public class work {
    public integer add(){
        integer a=40;
        integer b=40;
        integer z;
        z=a+b;
        system.debug('addition='+z);
     	return z;
        
        
    }
    public integer sub(){
        integer a=40;
        integer b=40;
        integer z;
        z=a-b;
        return z;
    }
    public integer mul(){
        integer a=40;
        integer b=40;
        integer z;
        z=a*b;
        return z;
        
    }
    public integer div(){
        integer a=40;
        integer b=40;
        integer z;
        z=a/b;
		return z;
    }

}